# Generated by Django 4.0.3 on 2022-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_car_concessionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionnaire',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
