# Generated by Django 4.0.3 on 2022-05-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='concessionnaire',
        ),
    ]
