# Generated by Django 4.0.3 on 2022-05-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_car_concessionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignConcessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('companyLocation', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=200)),
                ('companyDesc', models.TextField()),
            ],
            options={
                'verbose_name': 'ForeignConcessionnaire',
                'verbose_name_plural': 'ForeignConcessionnaires',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
        migrations.RenameField(
            model_name='concessionnaire',
            old_name='ville',
            new_name='companyLocation',
        ),
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='promotion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concessionnaire',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePublication', models.DateField()),
                ('idCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.car', verbose_name='car')),
                ('idConcessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.concessionnaire', verbose_name='concessionnaire')),
                ('idWebsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.website', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
