# Generated by Django 4.0.3 on 2022-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_foreignconcessionnaire_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='promotion',
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=50),
        ),
    ]
