# Generated by Django 4.0.4 on 2022-06-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_car_promotion_alter_car_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50, null=True)),
                ('mileage', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=50, null=True, verbose_name='cat')),
                ('img', models.ImageField(null=True, upload_to='photos')),
                ('description', models.TextField(null=True, verbose_name='write something')),
                ('gearbox', models.CharField(max_length=20, null=True)),
                ('fuel', models.CharField(max_length=20, null=True)),
                ('dateOfPub', models.CharField(max_length=20, null=True)),
                ('fiscalPower', models.IntegerField(max_length=20, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.concessionnaire', verbose_name='concessionnaire')),
            ],
            options={
                'verbose_name': 'ForeignCar',
                'verbose_name_plural': 'ForeignCars',
            },
        ),
    ]
