# Generated by Django 4.0.4 on 2022-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_car_color_car_dateofpub_car_fiscalpower_car_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='cat'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(null=True, verbose_name='write something'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
