# Generated by Django 4.0.3 on 2022-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_car_category_alter_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fiscalPower',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
