# Generated by Django 4.0.4 on 2022-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_car_fiscalpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastVisite1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(default='something', max_length=250, null=True),
        ),
    ]
